### ISSUE TITLE
GitHub Actions for Profile

### ISSUE THREAD

**Issue by scuervo91** [willmcgugan/willmcgugan#2]
Hi, I've been using rich for some projects and I think it is really great. I liked you idea of this repo to make your Github profile based on Rich. I would like to do the same and then I came out with an idea to create a Github Action to automatically create the readme.md file when some commit is made. 

So I tried to make this workflow but I'm sure I am missing some step to save the file. on the repo.
``` yml
name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install rich
      - run: python willmcgugan.py
```
If you know how this workflow can be completed I'd appreciate that!

Thank you

**Comment by scuervo91** [comment]
Hi.

I just found how to make this with this Action

```yml
name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install rich
      - run: python willmcgugan.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
I hope this helps!
